[package]
name = "osmosis-router"
version = "1.2.0"
authors = ["0xsquid"]
edition = "2021"

[dependencies]
cosmwasm-schema =  { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
bech32 = { workspace = true }
serde-json-wasm = { workspace = true }
serde-cw-value = { workspace = true }
schemars = { workspace = true }
osmosis-std = { workspace = true }
prost = { workspace = true }
itertools = {workspace = true}

sha2 = "0.10.6"
hex = "0.4.3"